DELETE http://localhost:3000/api/notes/67aa7f997f5368d69f807508


###
GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/67aa80df0767d8e7450fcec0


###
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "content": "HTML",
    "important": true
}

###
PUT http://localhost:3000/api/notes/67aa80df0767d8e7450fcec0
Content-Type: application/json

{
    "content": "MAs ricaaaaaaaaaaaaa",
    "important": true
}